version: 0.2

env:
  variables:
    DATABASE_HOST: "not-used"
    DATABASE_USER: "not-used"
    DATABASE_PASSWORD: "not-used"
    DATABASE_DB_NAME: "not-used"


phases:
  install:
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - nosetests --with-xunit --cover-xml --cover-xml-file=coverage.xml --with-coverage --cover-erase --cover-package=.
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  UnitTests: #
    files: #Store all of the files
      - 'nosetests.xml'
  NewCoverage: #
    files: #Store all of the files
      - 'coverage.xml'
    file-format: COBERTURAXML
