version: 0.2

phases:
  install:
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - nosetests --with-xunit
  post_build:
    commands:
      - echo Build completed on `date`

reports: #New
  UnitTests: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - 'nosetests.xml'
